# Generated by Django 2.0.5 on 2018-06-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.TextField(default='', max_length=50)),
                ('type', models.CharField(choices=[('Singles', 'Singles'), ('Doubles', 'Doubles')], max_length=7)),
                ('location', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
