# Generated by Django 2.0.5 on 2018-06-05 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20180605_2201'),
        ('ranking', '0002_auto_20180605_2153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ranking',
            new_name='ModelRanking',
        ),
    ]
