# Generated by Django 2.0.5 on 2018-06-05 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_auto_20180605_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='active',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='wins',
        ),
    ]
