# Generated by Django 2.0.5 on 2018-06-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0005_auto_20180605_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='numberOfPlayers',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
