# Generated by Django 2.0.5 on 2018-06-06 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0006_ranking_numberofplayers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking',
            options={'verbose_name': 'My image'},
        ),
    ]
