# Generated by Django 2.0.5 on 2018-06-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0007_auto_20180606_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking',
            options={'verbose_name': ('Ranked Tiers',)},
        ),
        migrations.AlterField(
            model_name='ranking',
            name='numberOfPlayers',
            field=models.IntegerField(default=0),
        ),
    ]
