# Generated by Django 2.0.5 on 2018-06-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0008_auto_20180606_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking',
            options={'verbose_name': 'Ranked Tiers'},
        ),
    ]
